# Site settings
title: "Thoughts on Life and Technology"
description: "Just a place to collect my experiences and tell the world my thoughts"
baseurl: "ohmyitscasper.github.io"
url: "ohmyitscasper.github.io"

# Build settings
markdown: kramdown
permalink: pretty
