# Site settings
title: "Thoughts on Life"
email: "example@example.com"
description: "Just a place to collect my thoughts and tell the world about me and my experiences"
baseurl:  ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
