# Site settings
title: "Thoughts on Life"
email: "example@example.com"
description: "Just a place to collect my thoughts and tell the world about me and my experiences"
baseurl:  ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

analytics:
    provider: google
    google:
        tracking_id: 'UA-51708055-1'

